CREATE TABLE IF NOT EXISTS notes (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR NOT NULL,
	path VARCHAR NOT NULL,
	created_at DATEIME NOT NULL,
	last_edit DATEIME NOT NULL,
	parent VARCHAR,
	type VARCHAR
	);

CREATE TABLE IF NOT EXISTS tags (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	note_id VARCHAR NOT NULL,
	tag VARCHAR NOT NULL,
	FOREIGN KEY(note_id) REFERENCES notes(id)
	);

CREATE TABLE IF NOT EXISTS link (
	"from" INTEGER NOT NULL,
	"to" INTEGER NOT NULL,
	FOREIGN KEY("from") REFERENCES notes(id),
	FOREIGN KEY("to") REFERENCES notes(id)
	);


